# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Redactor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


def paint(self, painter):
    painter.setBrush(QtCore.Qt.NoBrush)
    pen = QtGui.QPen(QtCore.Qt.darkBlue, 8)
    painter.setPen(pen)
    p1 = self.in_point.get_pos_pipe()
    p2 = self.out_point.get_pos_pipe()
    # Собираем препятствия
    obstacles = []
    parent_widget = self.parent_widget
    connect_obj = getattr(self, 'connect_obj', None)

    if parent_widget:
        for obj in parent_widget.objects:
            if obj is self:
                continue
            if connect_obj and obj is connect_obj:
                continue
            rect = getattr(obj, "get_rect", lambda: None)()
            if isinstance(rect, QtCore.QRect) and rect.width() > 0 and rect.height() > 0:
                obstacles.append(rect)

    # Построение маршрута с обходом препятствий
    path_points = QPipe.build_orthogonal_path(p1, p2, obstacles)

    # Рисуем линию по маршруту
    path = QtGui.QPainterPath()
    path.moveTo(path_points[0])
    for pt in path_points[1:]:
        path.lineTo(pt)
    painter.drawPath(path)