# -*- coding: utf-8 -*-


# Form implementation generated from reading ui file 'asd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QListWidget, QMainWindow, QDockWidget
from PyQt5.QtGui import QPainter, QColor, QCursor, QPixmap
from PyQt5.QtCore import Qt, QPoint, QRect, pyqtSignal

class ElementController(QtCore.QObject):
    element_changed = QtCore.pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self._selected_element = None

    def set_element(self, name):
        self._selected_element = name
        self.element_changed.emit(name)

    def get_element(self):
        return self._selected_element


class DraggableObject:
    def __init__(self, x, y, size=100, color=QColor(100, 200, 150), image_path = None):
        self.position = QPoint(x, y)
        self.size = size
        self.color = color
        self.dragging = False
        self.image = QPixmap('icon/Default.png') if image_path is None else image_path


    def contains(self, point):
        rect = self.get_rect()
        return rect.contains(point)

    def get_rect(self):
        return QRect(self.position.x(), self.position.y(), self.size, self.size)


class QPump(DraggableObject):
    def __init__(self, x, y):
        image_path = QPixmap('icon/MOT.png')
        super().__init__(x, y, image_path)


class QMov(DraggableObject):
    def __init__(self, x, y):
        image_path = QPixmap('icon/MOV.png')
        super().__init__(x, y, image_path)


class QBoiler(DraggableObject):
    def __init__(self, x, y):
        image_path = QPixmap('icon/BOILER.png')
        super().__init__(x, y, image_path)


class QPipe(DraggableObject):
    def __init__(self, x, y):
        image_path = QPixmap('icon/PIPE.png')
        super().__init__(x, y, image_path)


class QFlowSource(DraggableObject):
    pass


class QPipeChange(DraggableObject):
    pass


class QPipeIntersection(DraggableObject):
    pass


class QFilter(DraggableObject):
    pass


class QCapacity(DraggableObject):
    pass


class QThermalFluid(DraggableObject):
    pass


class QValve(DraggableObject):
    pass


class WidgetWithObjects(QWidget):
    def __init__(self,parent, controller):
        super().__init__(parent)
        self.selected_element = None
        self.setGeometry(0, 0, 1300, 800)
        self.objects = [
            DraggableObject(100, 100),
            DraggableObject(300, 150),
            DraggableObject(500, 200)
        ]

        self.selected_object = None
        self.offset = QPoint()
        self.proximity_threshold = 0  # порог близости
        self.controller = controller
        self.selected_element = None
        self.controller.element_changed.connect(self.set_selected_element)

    def set_selected_element(self, element_name):
        self.selected_element = element_name

    def paintEvent(self, event):
        painter = QPainter(self)
        for obj in self.objects:
            if obj.image:
                painter.drawPixmap(obj.position.x(), obj.position.y(), obj.size, obj.size, obj.image)
            else:
                painter.drawPixmap(obj.position.x(), obj.position.y(), obj.size, obj.size)


    def mousePressEvent(self, event):
        if self.selected_element:
            pos = event.pos()
            if self.selected_element == "QPump":
                new_obj = QPump(pos.x(), pos.y())
            elif self.selected_element == "QMov":
                new_obj = QMov(pos.x(), pos.y())
            elif self.selected_element == "QBoiler":
                new_obj = QBoiler(pos.x(), pos.y())
            elif self.selected_element == "QPipe":
                new_obj = QPipe(pos.x(), pos.y())
            else:
                new_obj = DraggableObject(pos.x(), pos.y())
            self.objects.append(new_obj)
            self.update()
        else:
            self.setFocus()
            for obj in reversed(self.objects):
                if obj.contains(event.pos()):
                    self.selected_object = obj
                    obj.dragging = True
                    self.offset = event.pos() - obj.position
                    break

    def mouseMoveEvent(self, event):
        # Проверяем, есть ли выбранный объект и он в режиме перетаскивания
        if self.selected_object and self.selected_object.dragging:
            self.proximity_threshold = self.selected_object.size + 60
            # Вычисляем новую позицию объекта на основе текущей позиции мыши и смещения
            new_pos = event.pos() - self.offset

            # Проверка близости с другими объектами
            for other in self.objects:
                if other != self.selected_object:
                    # Расстояние между предполагаемой новой позицией и другим объектом
                    dist = (new_pos - other.position).manhattanLength()
                    # Если объекты слишком близко, прерываем перемещение
                    if dist < self.proximity_threshold:
                        return  # Остановка перемещения при близости

            # Если все проверки прошли успешно, обновляем позицию выбранного объекта
            self.selected_object.position = new_pos
            # Обновляем виджет, чтобы отобразить изменения
            self.update()


    def mouseReleaseEvent(self, event):
        if self.selected_object:
            self.selected_object.dragging = False
            self.selected_object = None

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_A:
            self.add_object()
        elif event.key() == Qt.Key_D:
            self.remove_selected_object()

    def add_object(self):
        local_pos = self.mapFromGlobal(QCursor.pos())
        new_obj = DraggableObject(x=local_pos.x(), y=local_pos.y(), size=50, color=QColor(100, 200, 150))
        self.objects.append(new_obj)
        self.update()

    def remove_selected_object(self):
        local_pos = self.mapFromGlobal(QCursor.pos())
        for x in self.objects:
            if x.position.x() < local_pos.x() < x.position.x() + 50 and x.position.y() < local_pos.y() < x.position.y() + 50:
                self.objects.remove(x)
        self.update()


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.add_element_bool = False
        self.add_element_obj = None
        self.selected_element = None  # Сохраняем выбранный элемент
        self.controller = ElementController()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1900, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setLayout(QVBoxLayout())
        centralwidget_geometr = QRect(MainWindow.geometry())
        self.centralwidget.setGeometry(centralwidget_geometr)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtWidgets.QDockWidget('Элементы',MainWindow)
        self.dockWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(220, 300))
        self.dockWidget.setStyleSheet("background-color: rgb(177, 177, 177);")
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.RightDockWidgetArea|QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        #self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents = QListWidget()
        self.dockWidgetContents.setIconSize(QtCore.QSize(48, 48))
        self.dockWidgetContents.setEnabled(True)
        self.dockWidgetContents.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockWidgetContents.setObjectName("dockWidgetContents")

        items = [
            ("QPump", "icon/MOT.png"),
            ("QMov", "icon/MOV.png"),
            ("QBoiler", "icon/BOILER.png"),
            ("QPipe", "icon/PIPE.png"),
        ]

        for name, icon_path in items:
            item = QtWidgets.QListWidgetItem(QtGui.QIcon(icon_path), name)
            self.dockWidgetContents.addItem(item)
        self.dockWidgetContents.currentItemChanged.connect(self.item_changed)
        # Создаем док-виджет и добавляем в него список
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.dockWidget)
        self.dockWidgetContents.currentItemChanged.connect(self.item_changed)
        self.actionMenu_Element = QtWidgets.QAction(MainWindow)
        self.actionMenu_Element.setObjectName("actionMenu_Element")
        self.menu_File.addAction(self.actionMenu_Element)
        self.menubar.addAction(self.menu_File.menuAction())


        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.redactor = WidgetWithObjects(self.centralwidget, self.controller)
        self.redactor.setGeometry(self.centralwidget.geometry())

    def item_changed(self, current, previous):
        if current:
            self.selected_element = current.text()
            self.controller.set_element(self.selected_element)  # Передаём выбранный элемент через контроллер
            print(f"Selected item: {current.text()}")




if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



# if __name__ == "__main__":
#     app = QApplication(sys.argv)
#     window = WidgetWithObjects()
#     window.show()
#     sys.exit(app.exec_())